# -*- coding: utf-8 -*-
"""teste_random_forest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fZoFdGM5vuQ0D0eA6DFvjFtWrG-TLVeu

# Notebook de teste da Random Forest para Daytrade

## 1️⃣ Imports e Configuração Inicial
"""

# !pip install pandas
# !pip install scikit-learn
# !pip install matplotlib
# !pip install seaborn


import pandas as pd
import numpy as np


from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score


import matplotlib.pyplot as plt
import seaborn as sns


pd.set_option('display.max_columns', None)

"""## 2️⃣ Carregamento dos Dados"""

df = pd.read_csv('C:\Users\Jurandir\OneDrive - CMC\Documentos\Scripts de investimento\SARs\data\logs antigos\sar_sinais.csv', parse_dates=['data'])


df.head()

"""## 3️⃣ Limpeza e Seleção dos Dados

Posteriormente vamos treinar somente com sinais APROVADOS (o robô teria entrado neles).
"""

# df = df[df['status'] == 'APROVADO'].copy()

"""Criamos o label binário:"""

df['y'] = (df['resultado_teorico'] == 'WIN').astype(int)

"""## 4️⃣ Engenharia de Features

Selecionamos apenas informações que estariam disponíveis no momento da decisão:
"""

X = df[[
'adx',
'ema_ok',
'adx_ok'
]]


y = df['y']

# X = df[[
#     'direcao_sar'
#     'tendencia_ema',
#     'ema_ok',
#     'adx',
#     'adx_ok'
# ]]


# y = df['y']

"""Converter booleanos:"""

X['ema_ok'] = X['ema_ok'].astype(str).map({'True': 1, 'False': 0})
X['adx_ok'] = X['adx_ok'].astype(str).map({'True': 1, 'False': 0})

"""## 5️⃣ Split Treino / Teste"""

X_train, X_test, y_train, y_test = train_test_split(
X, y,
test_size=0.3,
random_state=42,
stratify=y
)

"""## 6️⃣ Treinamento do Random Forest"""

model = RandomForestClassifier(
n_estimators=300,
max_depth=6,
min_samples_leaf=20,
random_state=42,
class_weight='balanced'
)


model.fit(X_train, y_train)

"""## 7️⃣ Avaliação do Modelo"""

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

"""Relatório"""

print(classification_report(y_test, y_pred))

"""Matriz de Confusão"""

cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', xticklabels=['Loss', 'Win'], yticklabels=['Loss', 'Win'])
plt.xlabel('Predito')
plt.ylabel('Real')
plt.title('Matriz de Confusão: Real vs. Predito (0=Loss, 1=Win)')
plt.show()

"""AUC ROC"""

roc_auc_score(y_test, y_prob)

"""## 8️⃣ Importância das Features"""

importances = pd.Series(
model.feature_importances_,
index=X.columns
).sort_values(ascending=False)


importances.plot(kind='bar', title='Importância das Features')
plt.show()

"""👉 Isso mostra o que realmente importa para o mercado, não o que achamos.

## 9️⃣ Simulação de Filtro Inteligente

Aceitar apenas sinais com probabilidade ≥ 60%:
"""

df['prob_win'] = model.predict_proba(X)[:, 1]


filtro_ia = df[df['prob_win'] >= 0.6]


print('Trades antes:', len(df))
print('Trades após IA:', len(filtro_ia))
print('Win rate original:', df['y'].mean())
print('Win rate IA:', filtro_ia['y'].mean())

"""## 🔟 Exportar o modelo"""

# Salva os arquivos
# joblib.dump(model, "rf_model.pkl")
# joblib.dump(scaler, "scaler.pkl")